# Generated by Django 3.0.8 on 2020-07-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200707_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'SCHEDULED'), ('rescheduled', 'RESCHEDULED'), ('completed', 'COMPLETED')], default='scheduled', max_length=11, null=True),
        ),
    ]
