# Generated by Django 3.0.8 on 2020-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200707_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(default='abc@xyz.com', max_length=254),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Gov', max_length=100),
        ),
    ]
